version: '3.9'

services:
  redis:
    container_name: "yofik-messenger-redis"
    image: redis
    networks:
      yofik-net:
        ipv4_address: 172.25.0.5

  db:
    container_name: "yofik-messenger-db"
    image: postgres
    environment:
      POSTGRES_USER: messenger
      POSTGRES_PASSWORD: messenger
      POSTGRES_DB: messenger
    networks:
      yofik-net:
        ipv4_address: 172.25.0.2

#  auth:
#    container_name: "yofik-messenger-auth"
#    build: auth
#    depends_on:
#      - db
#    networks:
#      yofik-net:
#        ipv4_address: 172.25.0.3

#  messenger:
#    container_name: "yofik-messenger-messenger"
#    build: messenger
#    depends_on:
#      - db
#      - redis
#    networks:
#      yofik-net:
#        ipv4_address: 172.25.0.4

networks:
  yofik-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
