spring:
  datasource:
    url: jdbc:postgresql://db/messenger
    username: messenger
    password: messenger

logging:
  level:
    root: INFO

server:
  port: 65100

auth:
  hmac256-key: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed egestas facilisis nisi ac auctor. Curabitur dictum iaculis leo, eu fringilla risus iaculis sit amet. Nullam ac massa sed diam sagittis pulvinar non eu orci. Cras consequat turpis non imperdiet lacinia. Nulla aliquet non diam vitae pharetra. Sed non libero fringilla, sodales orci pellentesque, tincidunt est. Nulla facilisi. Maecenas quis accumsan ipsum, nec consectetur sem. Mauris ac velit ac massa laoreet finibus et vitae orci. Aenean vel viverra odio. Suspendisse vitae nunc vitae quam feugiat euismod. Mauris tincidunt massa a sagittis fringilla. Nam eget semper arcu. Phasellus erat erat, porta in.
