spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true

yofik:
  messenger:
    user-agent: Athena Messenger
  api:
    auth-host: yofik.messenger.auth
    auth-port: 8081
  security:
    client-token: <client-token>

logging:
  level:
    org:
      hibernate:
        SQL: WARN
        type:
          descriptor:
            sql:
              BasicBinder: WARN