server:
  port: 8080
  ssl:
    enabled: false
    protocol: TLS
    enabled-protocols: TLSv1.2
    key-store: certs/Server-keystore.p12
    key-store-type: PKCS12
    key-store-password: password
    client-auth: need
    trust-store: certs/Server-truststore.p12
    trust-store-type: PKCS12
    trust-store-password: password

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/messenger
    username: messenger
    password: messenger
  jpa:
    hibernate:
      ddl-auto: validate
  redis:
    host: localhost
    port: 6379
    ssl: false

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
    algorithm: PBEWithMD5AndDES