spring:
  liquibase:
    change-log: db/changelog/db-changelog.xml
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: WARN
        type:
          descriptor:
            sql:
              BasicBinder: WARN