minio.url=http://localhost:9000
minio.access.name=ADMIN
minio.access.secret=ADMIN111
  
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=400KB
spring.servlet.multipart.max-file-size=20480MB
spring.servlet.multipart.max-request-size=21000MB