spring:
  profiles:
    active: dev

  liquibase:
    change-log: db/changelog/db-changelog.xml

  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    hibernate:
      ddl-auto: validate

  devtools:
    restart:
      enabled: true

athena:
  auth:
    preconfigured-admin:
      login: admin
      password: 12345678