server:
  port: 8082
  ssl:
    enabled: false
    protocol: TLS
    enabled-protocols: TLSv1.2
    key-store: certs/Server-keystore.p12
    key-store-type: PKCS12
    key-store-password: password
    client-auth: need
    trust-store: certs/Server-truststore.p12
    trust-store-type: PKCS12
    trust-store-password: password

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
    algorithm: PBEWithMD5AndDES