name: Deploy to yandex cloud

on: workflow_dispatch

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - uses: actions/upload-artifact@v3
        with:
          name: ready auth war
          path: auth/build/libs/auth-0.3.0.war
          retention-days: 1
      - uses: actions/upload-artifact@v3
        with:
          name: ready messenger war
          path: messenger/build/libs/messenger-0.3.0.war
          retention-days: 1
  deploy:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate in Docker Registry
        run: |
          docker login --username json_key --password "$YANDEX_CLOUD_SERVICE_ACC_JSON_KEY" cr.yandex
        env:
          YANDEX_CLOUD_SERVICE_ACC_JSON_KEY: ${{ secrets.YANDEX_CLOUD_SERVICE_ACC_JSON_KEY }}
      - name: Obtain auth war
        uses: actions/download-artifact@v3
        with:
          name: ready auth war
      - name: Obtain messenger war
        uses: actions/download-artifact@v3
        with:
          name: ready messenger war
      - name: Build and push docker images
        run: |
          mkdir auth-deploy/ &&
          cp auth-0.3.0.war auth-deploy/ &&
          echo -e 'FROM openjdk:11\nCOPY auth-0.3.0.war /app/app.war' >> auth-deploy/Dockerfile &&
          docker build --tag cr.yandex/crp5k3dr812s2e3dqnt7/auth-service:latest auth-deploy &&
          docker push cr.yandex/crp5k3dr812s2e3dqnt7/auth-service:latest &&
          mkdir messenger-deploy/ &&
          cp messenger-0.3.0.war messenger-deploy &&
          echo -e 'FROM openjdk:11\nCOPY messenger-0.3.0.war /app/app.war' >> messenger-deploy/Dockerfile &&
          docker build --tag cr.yandex/crp5k3dr812s2e3dqnt7/messenger-service:latest messenger-deploy &&
          docker push cr.yandex/crp5k3dr812s2e3dqnt7/messenger-service:latest
          END
